# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields:
  nyt_api_key: "{{ env.NYT_API_KEY }}"
  nyt_book_list: hardcover-fiction
  nyt_display: covers
  display_count: "10"
  show_debug: "no"

# Sample data for preview
sample_data:
  status: "OK"
  copyright: "Copyright (c) 2023 The New York Times Company. All Rights Reserved."
  num_results: 15
  last_modified: "2023-07-05T22:04:28-04:00"
  results:
    bestsellers_date: "2023-07-01"
    published_date: "2023-07-16"
    published_date_description: "latest"
    previous_published_date: "2023-07-09"
    next_published_date: ""
    display_name: "Hardcover Fiction"
    list_name_encoded: "hardcover-fiction"
    updated: "WEEKLY"
    books:
      - rank: 1
        rank_last_week: 1
        weeks_on_list: 5
        asterisk: 0
        dagger: 0
        primary_isbn10: "0385547137"
        primary_isbn13: "9780385547130"
        publisher: "Doubleday"
        description: "The 23rd book in the Jack Reacher series. Reacher works to get an innocent woman out of prison."
        price: "0.00"
        title: "FOURTH WING"
        author: "Rebecca Yarros"
        contributor: "by Rebecca Yarros"
        contributor_note: ""
        book_image: "https://storage.googleapis.com/du-prd/books/images/9781649374042.jpg"
        book_image_width: 333
        book_image_height: 500
        amazon_product_url: "https://www.amazon.com/dp/1649374046?tag=NYTBSREV-20"
        age_group: ""
        book_review_link: ""
        first_chapter_link: ""
        sunday_review_link: ""
        article_chapter_link: ""
        isbns:
          - isbn10: "1649374046"
            isbn13: "9781649374042"
      - rank: 2
        rank_last_week: 2
        weeks_on_list: 7
        asterisk: 0
        dagger: 0
        primary_isbn10: "1649374046"
        primary_isbn13: "9781649374042"
        publisher: "Red Tower"
        description: "Violet Sorrengail is urged by the commanding general, who also is her mother, to become a candidate for the elite dragon riders."
        price: "0.00"
        title: "HAPPY PLACE"
        author: "Emily Henry"
        contributor: "by Emily Henry"
        contributor_note: ""
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780593441275.jpg"
        book_image_width: 331
        book_image_height: 500
        amazon_product_url: "https://www.amazon.com/dp/0593441273?tag=NYTBSREV-20"
        age_group: ""
        book_review_link: ""
        first_chapter_link: ""
        sunday_review_link: ""
        article_chapter_link: ""
        isbns:
          - isbn10: "0593441273"
            isbn13: "9780593441275"
      - rank: 3
        rank_last_week: 6
        weeks_on_list: 4
        asterisk: 0
        dagger: 0
        primary_isbn10: "0316404578"
        primary_isbn13: "9780316404570"
        publisher: "Little, Brown"
        description: "The eighth book in the Cormoran Strike series. Private detective Cormoran Strike's business partner disappears when she tries to visit a dying relative."
        price: "0.00"
        title: "THE RUNNING GRAVE"
        author: "Robert Galbraith"
        contributor: "by Robert Galbraith"
        contributor_note: ""
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780316404570.jpg"
        book_image_width: 329
        book_image_height: 500
        amazon_product_url: "https://www.amazon.com/dp/0316404578?tag=NYTBSREV-20"
        age_group: ""
        book_review_link: ""
        first_chapter_link: ""
        sunday_review_link: ""
        article_chapter_link: ""
        isbns:
          - isbn10: "0316404578"
            isbn13: "9780316404570"
      - rank: 4
        rank_last_week: 3
        weeks_on_list: 8
        asterisk: 0
        dagger: 0
        primary_isbn10: "0593441273"
        primary_isbn13: "9780593441275"
        publisher: "Berkley"
        description: "A former couple pretend to be together for the sake of their friends during their annual getaway."
        price: "0.00"
        title: "ICEBREAKER"
        author: "Hannah Grace"
        contributor: "by Hannah Grace"
        contributor_note: ""
        book_image: "https://storage.googleapis.com/du-prd/books/images/9781668026038.jpg"
        book_image_width: 327
        book_image_height: 500
        amazon_product_url: "https://www.amazon.com/dp/1668026031?tag=NYTBSREV-20"
        age_group: ""
        book_review_link: ""
        first_chapter_link: ""
        sunday_review_link: ""
        article_chapter_link: ""
        isbns:
          - isbn10: "1668026031"
            isbn13: "9781668026038"
      - rank: 5
        rank_last_week: 4
        weeks_on_list: 5
        asterisk: 0
        dagger: 0
        primary_isbn10: "1668026031"
        primary_isbn13: "9781668026038"
        publisher: "Atria"
        description: "Anastasia might be the only woman who can help the captain of a college hockey team improve his game."
        price: "0.00"
        title: "CROSS DOWN"
        author: "James Patterson and Brendan DuBois"
        contributor: "by James Patterson and Brendan DuBois"
        contributor_note: ""
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780316402873.jpg"
        book_image_width: 322
        book_image_height: 500
        amazon_product_url: "https://www.amazon.com/dp/0316402877?tag=NYTBSREV-20"
        age_group: ""
        book_review_link: ""
        first_chapter_link: ""
        sunday_review_link: ""
        article_chapter_link: ""
        isbns:
          - isbn10: "0316402877"
            isbn13: "9780316402873"

# override variables
variables:
  trmnl: { plugin_settings: { instance_name: "NYT Best Sellers" } }
